### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by xKotelek** [LezdCS/irl-link#147] opened 2023-12-22 20:05 UTC
Every time me on ios od my friend on android try to login we get error 405![image](https://github.com/LezdCS/irl-link/assets/98203141/c8c5bb2e-e08d-4b57-9219-7093da4d5033)

**Comment by LezdCS** [comment] 2023-12-22 22:54
Oh that's odd, I can't reproduce it, let me check what could cause this on server side

**Comment by gvsyn** [comment] 2023-12-23 00:22
![image](https://github.com/LezdCS/irl-link/assets/223082/f46dfd2a-226b-47cc-b4eb-5cb4d275023a)
Had the same since the 16th... Did you utterly clear your cache before trying to reproduce? (suspecting everything expired on my end)

**Comment by xKotelek** [comment] 2023-12-23 06:31
> ![image](https://github.com/LezdCS/irl-link/assets/223082/f46dfd2a-226b-47cc-b4eb-5cb4d275023a)
> 
> Had the same since the 16th... Did you utterly clear your cache before trying to reproduce? (suspecting everything expired on my end)

no

**Comment by xKotelek** [comment] 2023-12-23 06:35
i cleared cache reinstalled app and still error 405

**Comment by xKotelek** [comment] 2023-12-24 15:40
> Oh that's odd, I can't reproduce it, let me check what could cause this on server side
now i keep getting error 400![image](https://github.com/LezdCS/irl-link/assets/98203141/094add7a-e27b-477b-aabc-c3cd959f74e8)

**Comment by LezdCS** [comment] 2024-01-06 18:00
Sorry for the delay, I was away for holidays, I pushed a fix on the server yesterday, could you tell me if you still get the error ?

**Comment by gvsyn** [comment] 2024-01-07 03:14
> Sorry for the delay, I was away for holidays, I pushed a fix on the server yesterday, could you tell me if you still get the error ?

Not any more. Thanks.

**Closed** 2024-01-08 18:17 UTC
